/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmaCalculadora {
        /**
          * Permite establecer la coma como separador decimal
         */
        "comaDecimal": boolean;
        /**
          * Restaura la calculadora a su valor inicial
          * @param valor Valor inicial en pantalla, 0 por defecto
          * @returns Promesa resuelta
         */
        "init": (valor?: number) => Promise<void>;
        /**
          * Permite establecer el valor inicial
         */
        "value": number;
    }
}
export interface JmaCalculadoraCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJmaCalculadoraElement;
}
declare global {
    interface HTMLJmaCalculadoraElement extends Components.JmaCalculadora, HTMLStencilElement {
    }
    var HTMLJmaCalculadoraElement: {
        prototype: HTMLJmaCalculadoraElement;
        new (): HTMLJmaCalculadoraElement;
    };
    interface HTMLElementTagNameMap {
        "jma-calculadora": HTMLJmaCalculadoraElement;
    }
}
declare namespace LocalJSX {
    interface JmaCalculadora {
        /**
          * Permite establecer la coma como separador decimal
         */
        "comaDecimal"?: boolean;
        /**
          * El evento "equaled" se dispara cuando se pulsa el = y se obtiene el resultado total
         */
        "onEqualed"?: (event: JmaCalculadoraCustomEvent<number>) => void;
        /**
          * El evento "updated" se dispara cuando se calcula un nuevo resultado
         */
        "onUpdated"?: (event: JmaCalculadoraCustomEvent<number>) => void;
        /**
          * Permite establecer el valor inicial
         */
        "value"?: number;
    }
    interface IntrinsicElements {
        "jma-calculadora": JmaCalculadora;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jma-calculadora": LocalJSX.JmaCalculadora & JSXBase.HTMLAttributes<HTMLJmaCalculadoraElement>;
        }
    }
}
