/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Demo de componente contador
     */
    interface MyContador {
        /**
          * Valor a incrementar/decrementar del contador
         */
        "delta": number;
        /**
          * Valor inicial del contador
         */
        "init": number;
        /**
          * Reinicia el contador
         */
        "reset": () => Promise<void>;
    }
}
export interface MyContadorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyContadorElement;
}
declare global {
    /**
     * Demo de componente contador
     */
    interface HTMLMyContadorElement extends Components.MyContador, HTMLStencilElement {
    }
    var HTMLMyContadorElement: {
        prototype: HTMLMyContadorElement;
        new (): HTMLMyContadorElement;
    };
    interface HTMLElementTagNameMap {
        "my-contador": HTMLMyContadorElement;
    }
}
declare namespace LocalJSX {
    /**
     * Demo de componente contador
     */
    interface MyContador {
        /**
          * Valor a incrementar/decrementar del contador
         */
        "delta"?: number;
        /**
          * Valor inicial del contador
         */
        "init"?: number;
        /**
          * Notifica los cambios en el contador
         */
        "onUpdated"?: (event: MyContadorCustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "my-contador": MyContador;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Demo de componente contador
             */
            "my-contador": LocalJSX.MyContador & JSXBase.HTMLAttributes<HTMLMyContadorElement>;
        }
    }
}
